export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAIL = 'CREATE_CARD_FAIL';
export const CREATE_CARDSET_SUCCESS = 'CREATE_CARDSET_SUCCESS';
export const CREATE_CARDSET_FAIL = 'CREATE_CARDSET_FAIL';

export const RETRIEVE_CARDS = 'RETRIEVE_CARDS';
export const RETRIEVE_CARDSETS = 'RETRIEVE_CARDSETS';

export const DELETE_CARDS = 'DELETE_CARDS';
export const DELETE_CARDSETS = 'DELETE_CARDSETS';

export const GET_NEXT_CARD = 'GET_NEXT_CARD';
export const GET_PREV_CARD = 'GET_PREV_CARD';