# Generated by Django 3.1.2 on 2020-11-12 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardsui', '0002_auto_20201018_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardsets', to=settings.AUTH_USER_MODEL),
        ),
    ]
