


//POST http://127.0.0.1:8000/account/login/
//Content-Type: application/json

//{
//    "username": "ryowright",
//    "password": "ryo31373"
//}



GET http://127.0.0.1:8000/account/user/
Content-Type: application/json
Authentication: "Token 3a13710e8173772e4b83d42aee63e1c609247f5d0c7aba749a84380e99bd7e01"
